### ISSUE TITLE
Colaboration options

### ISSUE THREAD

**Issue by Llewellynvdm** [jeremehancock/repo.ubuntuce.com#1]
Hi Jereme, trust your doing well.

I have, like many been looking at using Ubuntu as a child safe desktop solution, and was recently told about your project... 

Was very happy to see what you have done, written and made available here.

I working on a https://launchpad.net/cubic implementation. Was wondering if you would be interested to have a meetup of some sort.

**Comment by jeremehancock** [comment]
Hi,
I am very glad that you found UbuntuCE. I hope that it might be useful to you. I am not in a position to do a meetup. However, feel free to email me at michael [at] jeremehancock [dot] com if you would like to discuss anything.

Thanks, Jereme
