### ISSUE TITLE
Clearsigned file isn't valid, got 'NOSPLIT' error

### ISSUE THREAD

**Issue by TheRealNerdyDad** [jeremehancock/repo.ubuntuce.com#2]
After adding the key and the repo, I attempted to do an apt update and failed.   Running Ubuntu Budgie 20.04.4 LTS.   Here is the error:

`~$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease         
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease       
Get:4 https://repo.ubuntuce.com ./ InRelease                              
Err:4 https://repo.ubuntuce.com ./ InRelease                              
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease          
Hit:6 http://download.zerotier.com/debian/bionic bionic InRelease
Reading package lists... Done
E: Failed to fetch https://repo.ubuntuce.com/./InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://repo.ubuntuce.com ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Any ideas as to how I can fix this?

**Comment by jeremehancock** [comment]
Sorry to see you are having issues.

I just tested a fresh setup using the UbuntuCE Repo and I also got the error. I checked and it appeared that there was an issue with the SSL cert on github. However, when I read the issue with the SSL closer it showed that I  had an issue with the date and time on my system not being correct. So I checked my date and time settings and after correcting that `sudo apt update` worked correctly and I was able to add all the UbuntuCE packages.

Please let me know if this helps resolve your issue. I will leave this open until I hear back in case you are still having issues.

Thanks

**Comment by jeremehancock** [comment]
I just noticed there was also an issue in the repo. I just pushed an update for the repo that should fix things. I have been able to do multiple successful tests. Hopefully this will resolve your issues.

**Comment by TheRealNerdyDad** [comment]
Thanks.   I'm at work right now.   I'll try again when I get home tonight.

**Comment by TheRealNerdyDad** [comment]
That fixed the issue.   Thanks.

I'm not much of a programmer, more of a SysAdmin, but wanting to get more into DevOps.   Might be a tester if that would help you any.

**Comment by jeremehancock** [comment]
So glad that things are working now. I also appreciate you reporting the issue so I could fix it quickly. Reporting issues is one of the best ways to help honestly since it can be very difficult to test all the different scenarios. Thank you
