### ISSUE TITLE
Some apps for your users

### ISSUE THREAD

**Issue by hotlittlewhitedog** [jeremehancock/repo.ubuntuce.com#3]
Hi Jereme :) 

I found your Linux distribution on Distrowatch 👍 

I'm a Christian programmer and I made these Bible apps with my heart to serve the Lord.

The apps are not the most beautiful apps (if you have another it's fine for me), but I think they are useful.

My apps are offline, without ads, for KJV lovers in English, but also in French, Spanish, Portuguese, Italian. It's totally free :)
  
I would suggest you for your distro: The Life and The Son Of Man, working on Linux and having a Snap package. 

My source codes are on https://gitlab.com/hotlittlewhitedog

Don't hesitate to contact me, it would be a pleasure to see my apps on a distro 😄 

  
---
1) "The Light" (Android)

Contains Bible Audio and widgets.  
Works also on Android TV*, Chromebooks.  

* Google:
https://play.google.com/store/apps/details?id=org.hlwd.bible

* F-Droid:
https://f-droid.org/packages/org.hlwd.bible
  
  
  
---
2) "The Life" (Android, iPhone, iPad, Big Sur, Mac, Linux)

Simple app to read the Bible.  
Contains also a German Bible.

* iPhone, iPad, Big Sur:
https://apps.apple.com/us/app/bible-multi-the-life/id1502832136 

* Mac: 
https://apps.apple.com/us/app/bible-multi-the-life/id1587163844

* Linux: 
https://snapcraft.io/bible-multi-the-life

* Google:
https://play.google.com/store/apps/details?id=org.hlwd.bible_multi_the_life 

* F-Droid:
https://f-droid.org/en/packages/org.hlwd.bible_multi_the_life

---
3)  "The Son Of Man"

Terminal app. 

* Snap (Linux):
https://snapcraft.io/bible-multi-the-son-of-man

* Flatpak (Linux): 
https://flathub.org/apps/details/org.hlwd.sonofman

* PyPI (Linux, Mac, Raspberry, all ARM): 
https://pypi.org/project/sonofman/

** All The Glory to God ❤️ ❤️ 

https://t.me/biblemultithelight

**Comment by jeremehancock** [comment]
Thank you for the suggestions! We are going to add Son of Man using Flatpak into the next release of UbuntuCE. I am actively working on it now. Adding Snap packages has proven difficult so if you have a Flatpak for your other apps please let us know and we can review those for inclusion as well.

Thanks, Jereme

**Comment by hotlittlewhitedog** [comment]
Hi Jereme @jeremehancock  

Yes I have a recent [Flatpak for "The Life"](https://flathub.org/apps/org.biblemulti.thelife)

Thanks for your help 👍 🎖️ 

** All The Glory To God ❤️
